import { readFile, writeFile, mkdir } from "node:fs/promises";
import path from "node:path";
import ts from "typescript";

const root = process.cwd();
const entries = JSON.parse(await readFile("data/entries.json", "utf8"));
const lock = JSON.parse(await readFile("package-lock.json", "utf8"));
const output = "data/generated";
await mkdir(output, { recursive: true });
const slugs = new Set();
for (const entry of entries) {
  if (slugs.has(entry.slug)) throw Error(`Duplicate component: ${entry.slug}`);
  if (!entry.description?.trim()) throw Error(`Missing description: ${entry.slug}`);
  slugs.add(entry.slug);
}
await writeFile(
  `${output}/preview-registry.ts`,
  `// Generated by scripts/buildCatalog.mjs.\n"use client";\nimport dynamic from "next/dynamic";\nimport { createElement, type ComponentType } from "react";\nconst loading = () => createElement("div", { "data-preview-loading": "true" });\nexport const demos: Record<string, ComponentType> = {\n${entries.map((entry) => `  "${entry.slug}": dynamic(() => import("../../registry/demos/${entry.slug}"), { ssr: false, loading }),`).join("\n")}\n};\n`,
);
const language = (file) =>
  file.endsWith(".tsx")
    ? "tsx"
    : file.endsWith(".ts")
      ? "typescript"
      : file.endsWith(".css")
        ? "css"
        : file.endsWith(".svg")
          ? "xml"
          : file.endsWith(".json")
            ? "json"
            : file.endsWith(".md")
              ? "markdown"
              : file.endsWith(".mjs")
                ? "javascript"
                : "text";
for (const entry of entries) {
  const files = new Map(),
    deps = new Set(["react", "react-dom"]),
    groups = new Set();
  let media = false;
  async function visit(file) {
    file = file.split(path.sep).join("/");
    if (files.has(file)) return;
    const content = await readFile(path.join(root, file), "utf8");
    files.set(file, { path: file, content, language: language(file) });
    if (content.includes("/media/")) media = true;
    const group = file.split("/")[1];
    if (["kokonut", "smoothui", "beui", "magicui"].includes(group)) groups.add(group);
    if (!/\.[tj]sx?$/.test(file)) return;
    const ast = ts.createSourceFile(
      file,
      content,
      ts.ScriptTarget.Latest,
      true,
      file.endsWith("tsx") ? ts.ScriptKind.TSX : ts.ScriptKind.TS,
    );
    const imports = [];
    function scan(node) {
      if (
        (ts.isImportDeclaration(node) || ts.isExportDeclaration(node)) &&
        node.moduleSpecifier &&
        ts.isStringLiteral(node.moduleSpecifier)
      )
        imports.push(node.moduleSpecifier.text);
      ts.forEachChild(node, scan);
    }
    scan(ast);
    for (const spec of imports) {
      if (spec.startsWith(".")) {
        const target = path.normalize(path.join(path.dirname(file), spec));
        let found = false;
        for (const candidate of [
          target,
          target + ".tsx",
          target + ".ts",
          path.join(target, "index.tsx"),
        ]) {
          try {
            await readFile(path.join(root, candidate));
          } catch {
            continue;
          }
          await visit(candidate);
          found = true;
          break;
        }
        if (!found) throw Error(`Unresolved import ${spec} in ${file}`);
      } else {
        if (spec.startsWith("@/") || spec.startsWith("@repo/") || spec.startsWith("next"))
          throw Error(`Non-portable import: ${spec}`);
        deps.add(spec.startsWith("@") ? spec.split("/").slice(0, 2).join("/") : spec.split("/")[0]);
      }
    }
  }
  // Main source is shown first; every transitive dependency is exported.
  await visit(entry.path);
  const demo = `registry/demos/${entry.slug}.tsx`;
  await visit(demo);
  await visit("registry/demo.css");
  if (media) for (let n = 1; n <= 6; n++) await visit(`public/media/art-0${n}.svg`);
  await visit("licenses/elements.txt");
  for (const group of groups) await visit(`licenses/${group}.txt`);
  if (files.has("registry/kokonut/Button.tsx") || files.has("registry/kokonut/Card.tsx"))
    await visit("licenses/shadcn.txt");
  if (deps.has("@fontsource/pacifico")) await visit("licenses/pacifico.txt");
  const dependencies = Object.fromEntries(
    [...deps].sort().map((name) => {
      const version = lock.packages[`node_modules/${name}`]?.version;
      if (!version) throw Error("Missing installed dependency: " + name);
      return [name, version];
    }),
  );
  const usage = `import Demo from "./${demo.replace(/\.tsx$/, "")}";\nimport "./registry/demo.css";\n\nexport default function App() {\n  return <Demo />;\n}\n`;
  files.set("App.tsx", { path: "App.tsx", content: usage, language: "tsx" });
  const install = `npm install ${Object.entries(dependencies)
    .map(([name, version]) => `${name}@${version}`)
    .join(" ")}`;
  const setup = `# ${entry.title}\n\n${install}\n\nnpm install -D tailwindcss@4 @tailwindcss/postcss@4 postcss\n\nUse a React + TypeScript project. Set up Tailwind CSS v4 with the @tailwindcss/postcss plugin (or @tailwindcss/vite for Vite). Copy these files keeping their relative paths. Import registry/demo.css once in your app. It contains Tailwind sources, theme tokens, and keyframes required by the example. Place public/media assets at /media on your server. The .dark class on the html element activates dark variants.\n\nApp.tsx is a working example; registry/demos/${entry.slug}.tsx shows the component API. The DemoFrame helper only controls the example layout. You may remove it when integrating the component. Keep the copyright notices and the included license files.\n\nOriginal source: ${entry.sourceUrl}\nPinned revision: ${entry.commit}\n\nThe catalog changed module paths, replaced Next.js-only adapters with plain React, and replaced sample media with local vector artwork. The examples include small accessibility, React 19, and demo behavior fixes. Original component visual styles are retained.\n`;
  files.set("INSTALL.md", { path: "INSTALL.md", content: setup, language: "markdown" });
  const all = [...files.values()];
  const prompt = `Implement the following ${entry.title} component in my React project. Preserve its appearance and interaction. Adapt only the import paths and integration points required by my project. Do not omit helper files, styles, assets, or license notices. Use the included working Demo and App.tsx as the integration reference. Respect prefers-reduced-motion and keyboard interaction. If my project already has Tailwind CSS, merge the provided tokens and keyframes with the existing stylesheet rather than replacing it.\n\n${setup}\n\nFILES\n\n${all.map((file) => `--- ${file.path} ---\n\`\`\`${file.language}\n${file.content}\n\`\`\``).join("\n\n")}`;
  await writeFile(
    `${output}/${entry.slug}.json`,
    JSON.stringify({ files: all, dependencies, usage, prompt }),
  );
}
console.log(`Built ${entries.length} complete source bundles from their live demo imports.`);
